### ISSUE TITLE
Encountered a problem when running the program, need some help

### ISSUE THREAD

**Issue by Bxbc** [rhhao/csMR#2]
When using a linux serve(4 core & 8G) to run this job on the example data you suggest, I can' t get the result after around 5-6 hours cost. And the snakemake log shows the info as below:
<img width="962" alt="image" src="https://github.com/user-attachments/assets/72f4f007-8b37-4fcc-8ca9-d1903704ff7e">

Could you give me some tips on how to solve this error? Thank you very much!

**Comment by LockenLiu** [comment]
hi, you should try the command shown in the error message to check the exact error: 
python scripts/split.
_GWAS_ma-py -ma /home/medical/CMR/example/BMI_GWAS/BMI_giant_ukbb_combined_2018.chr1-ma -w 100000
-r /home/medical/csMR/data/reference_genome_1000G_EUR -id BMI_Giant_UKB -0 CSMR-EXAMPLE
