### ISSUE TITLE
Error while running susie_finemap.py

### ISSUE THREAD

**Issue by HongyuanChu** [rhhao/csMR#5]
Error in susie_suff_stat(XtX = XtX, Xty = Xty, n = n, yty = (n - 1) *  : 
  The estimated prior variance is unreasonably large.
	     This is usually caused by mismatch between the summary statistics and the LD matrix.
             Please check the input.
running max iterations: 10000

**My Commend**:python /data/chuhy/packs/csMR-main/scripts/susie_finemap.py -o /data/chuhy/project/GWAS/work -d '{"epi":"cc"}' -c 0.9 -j 15

**My Log:**
/data/chuhy/project/GWAS/work/precomputation/Astrocytes.eQTL_split/9_86428858_86628858--GKAP1--Astrocytes.maf.raw.RData
/data/chuhy/project/GWAS/work/precomputation/Astrocytes.eQTL_split/2_166524469_166724469--GALNT3--Astrocytes.maf.raw.RData
/data/chuhy/project/GWAS/work/precomputation/Astrocytes.eQTL_split/9_86689306_86889306--KIF27--Astrocytes.maf.raw.RData
/data/chuhy/project/GWAS/work/precomputation/Astrocytes.eQTL_split/10_103430438_103630438--PSD--Astrocytes.maf.raw.RData
/data/chuhy/project/GWAS/work/precomputation/Astrocytes.eQTL_split/10_103875793_104075793--POLL--Astrocytes.maf.raw.RData
/data/chuhy/project/GWAS/work/precomputation/Astrocytes.eQTL_split/9_86666265_86868671--NTRK2--Astrocytes.maf.raw.RData
/data/chuhy/project/GWAS/work/precomputation/Astrocytes.eQTL_split/2_166557242_166765310--TTC21B--Astrocytes.maf.raw.RData
This is coloc version 5.2.3
This is coloc version 5.2.3
[1] "susie finemapping ------------ /data/chuhy/project/GWAS/work/precomputation/epi.GWAS_split/10_103455611_103902408.maf.raw.RData"
[1] "susie finemapping ------------ /data/chuhy/project/GWAS/work/precomputation/epi.GWAS_split/2_166718404_167108773.maf.raw.RData"
running max iterations: 10000
This is coloc version 5.2.3
[1] "susie finemapping ------------ /data/chuhy/project/GWAS/work/precomputation/Astrocytes.eQTL_split/2_166524469_166724469--GALNT3--Astrocytes.maf.raw.RData"
running max iterations: 10000
running max iterations: 10000
This is coloc version 5.2.3
[1] "susie finemapping ------------ /data/chuhy/project/GWAS/work/precomputation/epi.GWAS_split/9_86452049_86698190.maf.raw.RData"
running max iterations: 10000
This is coloc version 5.2.3
[1] "susie finemapping ------------ /data/chuhy/project/GWAS/work/precomputation/Astrocytes.eQTL_split/9_86428858_86628858--GKAP1--Astrocytes.maf.raw.RData"
running max iterations: 10000
	converged: TRUE
[1] "Try susie1 succeed"
[1] "finemapping is succeed and done! /data/chuhy/project/GWAS/work/precomputation/Astrocytes.eQTL_split/9_86428858_86628858--GKAP1--Astrocytes.maf.0.9.susie.RData"
This is coloc version 5.2.3
[1] "susie finemapping ------------ /data/chuhy/project/GWAS/work/precomputation/Astrocytes.eQTL_split/9_86689306_86889306--KIF27--Astrocytes.maf.raw.RData"
running max iterations: 10000
Error in susie_suff_stat(XtX = XtX, Xty = Xty, n = n, yty = (n - 1) *  : 
  The estimated prior variance is unreasonably large.
	     This is usually caused by mismatch between the summary statistics and the LD matrix.
             Please check the input.
running max iterations: 10000
	converged: TRUE
[1] "Try susie1 succeed"
[1] "finemapping is succeed and done! /data/chuhy/project/GWAS/work/precomputation/Astrocytes.eQTL_split/9_86689306_86889306--KIF27--Astrocytes.maf.0.9.susie.RData"
	converged: TRUE
[1] "Try susie2 succeed"
[1] "finemapping is succeed and done! /data/chuhy/project/GWAS/work/precomputation/Astrocytes.eQTL_split/2_166524469_166724469--GALNT3--Astrocytes.maf.0.9.susie.RData"
This is coloc version 5.2.3
[1] "susie finemapping ------------ /data/chuhy/project/GWAS/work/precomputation/Astrocytes.eQTL_split/10_103430438_103630438--PSD--Astrocytes.maf.raw.RData"
running max iterations: 10000
	converged: TRUE
[1] "Try susie1 succeed"
[1] "finemapping is succeed and done! /data/chuhy/project/GWAS/work/precomputation/Astrocytes.eQTL_split/10_103430438_103630438--PSD--Astrocytes.maf.0.9.susie.RData"
This is coloc version 5.2.3
[1] "susie finemapping ------------ /data/chuhy/project/GWAS/work/precomputation/Astrocytes.eQTL_split/10_103875793_104075793--POLL--Astrocytes.maf.raw.RData"
running max iterations: 10000
	converged: TRUE
[1] "Try susie1 succeed"
[1] "finemapping is succeed and done! /data/chuhy/project/GWAS/work/precomputation/Astrocytes.eQTL_split/10_103875793_104075793--POLL--Astrocytes.maf.0.9.susie.RData"
This is coloc version 5.2.3
[1] "susie finemapping ------------ /data/chuhy/project/GWAS/work/precomputation/Astrocytes.eQTL_split/9_86666265_86868671--NTRK2--Astrocytes.maf.raw.RData"
running max iterations: 10000
	converged: TRUE
[1] "Try susie1 succeed"
[1] "finemapping is succeed and done! /data/chuhy/project/GWAS/work/precomputation/Astrocytes.eQTL_split/9_86666265_86868671--NTRK2--Astrocytes.maf.0.9.susie.RData"
This is coloc version 5.2.3
[1] "susie finemapping ------------ /data/chuhy/project/GWAS/work/precomputation/Astrocytes.eQTL_split/2_166557242_166765310--TTC21B--Astrocytes.maf.raw.RData"
running max iterations: 10000
	converged: TRUE
[1] "Try susie1 succeed"
[1] "finemapping is succeed and done! /data/chuhy/project/GWAS/work/precomputation/Astrocytes.eQTL_split/2_166557242_166765310--TTC21B--Astrocytes.maf.0.9.susie.RData"
Error in susie_suff_stat(XtX = XtX, Xty = Xty, n = n, yty = (n - 1) *  : 
  The estimated prior variance is unreasonably large.
	     This is usually caused by mismatch between the summary statistics and the LD matrix.
             Please check the input.
running max iterations: 10000
Error in susie_suff_stat(XtX = XtX, Xty = Xty, n = n, yty = (n - 1) *  : 
  The estimated prior variance is unreasonably large.
	     This is usually caused by mismatch between the summary statistics and the LD matrix.
             Please check the input.
running max iterations: 10000

**Comment by HongyuanChu** [comment]
See https://github.com/chr1swallace/coloc/issues/90; I completely replaced the susie finemapping step to solve this problem. (Maybe not the best way but worked)

**Comment by jasmine327** [comment]
> See [chr1swallace/coloc#90](https://github.com/chr1swallace/coloc/issues/90); I completely replaced the susie finemapping step to solve this problem. (Maybe not the best way but worked)看 [chr1swallace/coloc#90](https://github.com/chr1swallace/coloc/issues/90) ;我完全替换了susie Finemapping步骤来解决这个问题。 （也许不是最好的方法，但有效）

Could you please explain in detail how you completely replaced the SuSiE fine-mapping step to resolve this issue?

**Comment by HongyuanChu** [comment]
> > See [chr1swallace/coloc#90](https://github.com/chr1swallace/coloc/issues/90); I completely replaced the susie finemapping step to solve this problem. 
> 
> Could you please explain in detail how you completely replaced the SuSiE fine-mapping step to resolve this issue?

I replaced susie with abf coloc. This may take less time and be more convient. (But not Baysian). The following steps need to be adjusted accrodingliy.

**Comment by jasmine327** [comment]
> > > See [chr1swallace/coloc#90](https://github.com/chr1swallace/coloc/issues/90); I completely replaced the susie finemapping step to solve this problem.参见[chr1swallace/coloc#90](https://github.com/chr1swallace/coloc/issues/90) ；我完全替换了susie Finemapping步骤来解决这个问题。
> > 
> > 
> > Could you please explain in detail how you completely replaced the SuSiE fine-mapping step to resolve this issue?您能否详细解释一下您是如何完全替换 SuSiE 精细映射步骤来解决此问题的？
> 
> I replaced susie with abf coloc. This may take less time and be more convient. (But not recommended by the author because of shortcomings). The following steps need to be adjusted accrodingliy.我用 abf coloc 替换了 susie。这可能会花费更少的时间并且更方便。 （但由于缺点，笔者不推荐）。以下步骤需要根据情况进行调整。

In that case, could you find any positive results? I have tried using `coloc.abf`, but the PP.H4.abf values I obtained were all quite small.

**Comment by HongyuanChu** [comment]
> > > > See [chr1swallace/coloc#90](https://github.com/chr1swallace/coloc/issues/90); I completely replaced the susie finemapping step to solve this problem.参见[chr1swallace/coloc#90](https://github.com/chr1swallace/coloc/issues/90) ；我完全替换了susie Finemapping步骤来解决这个问题。
> > > 
> > > 
> > > Could you please explain in detail how you completely replaced the SuSiE fine-mapping step to resolve this issue?您能否详细解释一下您是如何完全替换 SuSiE 精细映射步骤来解决此问题的？
> > 
> > 
> > I replaced susie with abf coloc. This may take less time and be more convient. (But not recommended by the author because of shortcomings). The following steps need to be adjusted accrodingliy.我用 abf coloc 替换了 susie。这可能会花费更少的时间并且更方便。 （但由于缺点，笔者不推荐）。以下步骤需要根据情况进行调整。
> 
> In that case, could you find any positive results? I have tried using `coloc.abf`, but the PP.H4.abf values I obtained were all quite small.

I did find some positive results, with the PPH4 0.95-1.

**Comment by jasmine327** [comment]
> > > > > See [chr1swallace/coloc#90](https://github.com/chr1swallace/coloc/issues/90); I completely replaced the susie finemapping step to solve this problem.参见[chr1swallace/coloc#90](https://github.com/chr1swallace/coloc/issues/90) ；我完全替换了susie Finemapping步骤来解决这个问题。参见[chr1swallace/coloc#90](https://github.com/chr1swallace/coloc/issues/90) ；我完全替换了susie Finemapping步骤来解决这个问题。参见[chr1swallace/coloc#90](https://github.com/chr1swallace/coloc/issues/90) ；我完全替换了susie Finemapping步骤来解决这个问题。
> > > > 
> > > > 
> > > > Could you please explain in detail how you completely replaced the SuSiE fine-mapping step to resolve this issue?您能否详细解释一下您是如何完全替换 SuSiE 精细映射步骤来解决此问题的？
> > > 
> > > 
> > > I replaced susie with abf coloc. This may take less time and be more convient. (But not recommended by the author because of shortcomings). The following steps need to be adjusted accrodingliy.我用 abf coloc 替换了 susie。这可能会花费更少的时间并且更方便。 （但由于缺点，笔者不推荐）。以下步骤需要根据情况进行调整。
> > 
> > 
> > In that case, could you find any positive results? I have tried using `coloc.abf`, but the PP.H4.abf values I obtained were all quite small.那么，你能找到任何积极的结果吗？我尝试过使用`coloc.abf` ，但是我获得的 PP.H4.abf 值都非常小。
> 
> I did find some positive results, with the PPH4 0.95-1.我确实发现了一些积极的结果，PPH4 为 0.95-1。

May I ask if you are using the example data, the eight types of brain cell data from the single-cell-eqtl?

**Comment by HongyuanChu** [comment]
> > > > > > See [chr1swallace/coloc#90](https://github.com/chr1swallace/coloc/issues/90); I completely replaced the susie finemapping step to solve this problem.参见[chr1swallace/coloc#90](https://github.com/chr1swallace/coloc/issues/90) ；我完全替换了susie Finemapping步骤来解决这个问题。参见[chr1swallace/coloc#90](https://github.com/chr1swallace/coloc/issues/90) ；我完全替换了susie Finemapping步骤来解决这个问题。参见[chr1swallace/coloc#90](https://github.com/chr1swallace/coloc/issues/90) ；我完全替换了susie Finemapping步骤来解决这个问题。
> > > > > 
> > > > > 
> > > > > Could you please explain in detail how you completely replaced the SuSiE fine-mapping step to resolve this issue?您能否详细解释一下您是如何完全替换 SuSiE 精细映射步骤来解决此问题的？
> > > > 
> > > > 
> > > > I replaced susie with abf coloc. This may take less time and be more convient. (But not recommended by the author because of shortcomings). The following steps need to be adjusted accrodingliy.我用 abf coloc 替换了 susie。这可能会花费更少的时间并且更方便。 （但由于缺点，笔者不推荐）。以下步骤需要根据情况进行调整。
> > > 
> > > 
> > > In that case, could you find any positive results? I have tried using `coloc.abf`, but the PP.H4.abf values I obtained were all quite small.那么，你能找到任何积极的结果吗？我尝试过使用`coloc.abf` ，但是我获得的 PP.H4.abf 值都非常小。
> > 
> > 
> > I did find some positive results, with the PPH4 0.95-1.我确实发现了一些积极的结果，PPH4 为 0.95-1。
> 
> May I ask if you are using the example data, the eight types of brain cell data from the single-cell-eqtl?

Well, I did not run the example data
but here's some of my result line:
<img width="1514" alt="1728539616138" src="https://github.com/user-attachments/assets/e8f7aea0-e0ae-43d7-b18f-ac4bb3740c66">

**Comment by HongyuanChu** [comment]
> > > > > > > See [chr1swallace/coloc#90](https://github.com/chr1swallace/coloc/issues/90); I completely replaced the susie finemapping step to solve this problem.参见[chr1swallace/coloc#90](https://github.com/chr1swallace/coloc/issues/90) ；我完全替换了susie Finemapping步骤来解决这个问题。参见[chr1swallace/coloc#90](https://github.com/chr1swallace/coloc/issues/90) ；我完全替换了susie Finemapping步骤来解决这个问题。参见[chr1swallace/coloc#90](https://github.com/chr1swallace/coloc/issues/90) ；我完全替换了susie Finemapping步骤来解决这个问题。
> > > > > > 
> > > > > > 
> > > > > > Could you please explain in detail how you completely replaced the SuSiE fine-mapping step to resolve this issue?您能否详细解释一下您是如何完全替换 SuSiE 精细映射步骤来解决此问题的？
> > > > > 
> > > > > 
> > > > > I replaced susie with abf coloc. This may take less time and be more convient. (But not recommended by the author because of shortcomings). The following steps need to be adjusted accrodingliy.我用 abf coloc 替换了 susie。这可能会花费更少的时间并且更方便。 （但由于缺点，笔者不推荐）。以下步骤需要根据情况进行调整。
> > > > 
> > > > 
> > > > In that case, could you find any positive results? I have tried using `coloc.abf`, but the PP.H4.abf values I obtained were all quite small.那么，你能找到任何积极的结果吗？我尝试过使用`coloc.abf` ，但是我获得的 PP.H4.abf 值都非常小。
> > > 
> > > 
> > > I did find some positive results, with the PPH4 0.95-1.我确实发现了一些积极的结果，PPH4 为 0.95-1。
> > 
> > 
> > May I ask if you are using the example data, the eight types of brain cell data from the single-cell-eqtl?
> 
> Well, I did not run the example data but here's some of my result line: <img alt="1728539616138" width="1514" src="https://private-user-images.githubusercontent.com/158466423/375237669-e8f7aea0-e0ae-43d7-b18f-ac4bb3740c66.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1NDAwMDksIm5iZiI6MTcyODUzOTcwOSwicGF0aCI6Ii8xNTg0NjY0MjMvMzc1MjM3NjY5LWU4ZjdhZWEwLWUwYWUtNDNkNy1iMThmLWFjNGJiMzc0MGM2Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMFQwNTU1MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNDAwMjIxNjZkY2EzNDA2YmMzNmRjMTBjYjNkZmE5MDM4OTUyZWRhYWY4MTFjMTk2YTY4NmQ3NzhjM2RlZTBmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.0_1IlVxNHTRwu5BZYDtC9Xv0NjWZcZiAxPi1BLJRb0I">

And this is a brain-related disorder. There were 56 SNPs with PPH4>0.8. Maybe u can have a try in certain neurologic disorder?

**Comment by jasmine327** [comment]
Thank you very much for your patient responses. May I have your email for further communication?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "rhhao/csMR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月10日(星期四) 中午1:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [rhhao/csMR] Error while running susie_finemap.py (Issue #5)





        
See chr1swallace/coloc#90; I completely replaced the susie finemapping step to solve this problem.参见chr1swallace/coloc#90 ；我完全替换了susie Finemapping步骤来解决这个问题。参见chr1swallace/coloc#90 ；我完全替换了susie Finemapping步骤来解决这个问题。参见chr1swallace/coloc#90 ；我完全替换了susie Finemapping步骤来解决这个问题。
  
Could you please explain in detail how you completely replaced the SuSiE fine-mapping step to resolve this issue?您能否详细解释一下您是如何完全替换 SuSiE 精细映射步骤来解决此问题的？
  
I replaced susie with abf coloc. This may take less time and be more convient. (But not recommended by the author because of shortcomings). The following steps need to be adjusted accrodingliy.我用 abf coloc 替换了 susie。这可能会花费更少的时间并且更方便。 （但由于缺点，笔者不推荐）。以下步骤需要根据情况进行调整。
  
In that case, could you find any positive results? I have tried using coloc.abf, but the PP.H4.abf values I obtained were all quite small.那么，你能找到任何积极的结果吗？我尝试过使用coloc.abf ，但是我获得的 PP.H4.abf 值都非常小。
  
I did find some positive results, with the PPH4 0.95-1.我确实发现了一些积极的结果，PPH4 为 0.95-1。
  
May I ask if you are using the example data, the eight types of brain cell data from the single-cell-eqtl?
  
Well, I did not run the example data but here's some of my result line: 
  
And this is a brain-related disorder. There were 56 SNPs with PPH4&gt;0.8. Maybe u can have a try in certain neurologic disorder?

**Comment by jasmine327** [comment]
> > > > > > > > See [chr1swallace/coloc#90](https://github.com/chr1swallace/coloc/issues/90); I completely replaced the susie finemapping step to solve this problem.参见[chr1swallace/coloc#90](https://github.com/chr1swallace/coloc/issues/90) ；我完全替换了susie Finemapping步骤来解决这个问题。参见[chr1swallace/coloc#90](https://github.com/chr1swallace/coloc/issues/90) ；我完全替换了susie Finemapping步骤来解决这个问题。参见[chr1swallace/coloc#90](https://github.com/chr1swallace/coloc/issues/90) ；我完全替换了susie Finemapping步骤来解决这个问题。
> > > > > > > 
> > > > > > > 
> > > > > > > Could you please explain in detail how you completely replaced the SuSiE fine-mapping step to resolve this issue?您能否详细解释一下您是如何完全替换 SuSiE 精细映射步骤来解决此问题的？
> > > > > > 
> > > > > > 
> > > > > > I replaced susie with abf coloc. This may take less time and be more convient. (But not recommended by the author because of shortcomings). The following steps need to be adjusted accrodingliy.我用 abf coloc 替换了 susie。这可能会花费更少的时间并且更方便。 （但由于缺点，笔者不推荐）。以下步骤需要根据情况进行调整。
> > > > > 
> > > > > 
> > > > > In that case, could you find any positive results? I have tried using `coloc.abf`, but the PP.H4.abf values I obtained were all quite small.那么，你能找到任何积极的结果吗？我尝试过使用`coloc.abf` ，但是我获得的 PP.H4.abf 值都非常小。
> > > > 
> > > > 
> > > > I did find some positive results, with the PPH4 0.95-1.我确实发现了一些积极的结果，PPH4 为 0.95-1。
> > > 
> > > 
> > > May I ask if you are using the example data, the eight types of brain cell data from the single-cell-eqtl?请问您使用的示例数据是single-cell-eqtl中的八种脑细胞数据吗？
> > 
> > 
> > Well, I did not run the example data but here's some of my result line: <img alt="1728539616138" width="775" height="32.515625" src="https://private-user-images.githubusercontent.com/158466423/375237669-e8f7aea0-e0ae-43d7-b18f-ac4bb3740c66.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1NDAwMDksIm5iZiI6MTcyODUzOTcwOSwicGF0aCI6Ii8xNTg0NjY0MjMvMzc1MjM3NjY5LWU4ZjdhZWEwLWUwYWUtNDNkNy1iMThmLWFjNGJiMzc0MGM2Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMFQwNTU1MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNDAwMjIxNjZkY2EzNDA2YmMzNmRjMTBjYjNkZmE5MDM4OTUyZWRhYWY4MTFjMTk2YTY4NmQ3NzhjM2RlZTBmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.0_1IlVxNHTRwu5BZYDtC9Xv0NjWZcZiAxPi1BLJRb0I">好吧，我没有运行示例数据，但这是我的一些结果行：[ <img alt="1728539616138" width="775" height="32.515625" src="https://private-user-images.githubusercontent.com/158466423/375237669-e8f7aea0-e0ae-43d7-b18f-ac4bb3740c66.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1NDAwMDksIm5iZiI6MTcyODUzOTcwOSwicGF0aCI6Ii8xNTg0NjY0MjMvMzc1MjM3NjY5LWU4ZjdhZWEwLWUwYWUtNDNkNy1iMThmLWFjNGJiMzc0MGM2Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMFQwNTU1MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNDAwMjIxNjZkY2EzNDA2YmMzNmRjMTBjYjNkZmE5MDM4OTUyZWRhYWY4MTFjMTk2YTY4NmQ3NzhjM2RlZTBmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.0_1IlVxNHTRwu5BZYDtC9Xv0NjWZcZiAxPi1BLJRb0I"> ](https://private-user-images.githubusercontent.com/158466423/375237669-e8f7aea0-e0ae-43d7-b18f-ac4bb3740c66.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1NDAwMDksIm5iZiI6MTcyODUzOTcwOSwicGF0aCI6Ii8xNTg0NjY0MjMvMzc1MjM3NjY5LWU4ZjdhZWEwLWUwYWUtNDNkNy1iMThmLWFjNGJiMzc0MGM2Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMFQwNTU1MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNDAwMjIxNjZkY2EzNDA2YmMzNmRjMTBjYjNkZmE5MDM4OTUyZWRhYWY4MTFjMTk2YTY4NmQ3NzhjM2RlZTBmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.0_1IlVxNHTRwu5BZYDtC9Xv0NjWZcZiAxPi1BLJRb0I)
> 
> And this is a brain-related disorder. There were 56 SNPs with PPH4>0.8. Maybe u can have a try in certain neurologic disorder?这是一种与大脑相关的疾病。 PPH4>0.8的SNP有56个。也许你可以尝试治疗某些神经系统疾病？

Thank you very much for your patient responses. May I have your email for further communication?
